name: Terraform Provision & Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Apply Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Save ACR Login Server
      id: acr
      run: |
        ACR_NAME=$(terraform output -raw acr_login_server)
        echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT

  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build & Push to ACR
      run: |
        ACR="${{ needs.terraform.outputs.acr_name }}"
        SERVICES=("ingestion")

        az acr login --name $(echo $ACR | cut -d. -f1)

        for SERVICE in "${SERVICES[@]}"
        do
          docker build -t $ACR/$SERVICE:latest ./sourcecode/$SERVICE
          docker push $ACR/$SERVICE:latest
        done