name: Terraform Infra + Docker Build + Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-all:
    name: Provision ACR + Build + Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply Infra
        run: |
          set -euxo pipefail
          terraform -chdir=terraform/infra init
          terraform -chdir=terraform/infra apply -auto-approve

      - name: Get ACR Name
        id: get-acr
        run: |
          ACR_LOGIN_SERVER=$(terraform -chdir=terraform/infra output -raw acr_login_server)
          echo "ACR login server: $ACR_LOGIN_SERVER"
          echo "acr_login_server=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT

      - name: Docker Build & Push to ACR
        run: |
          set -euxo pipefail
          ACR_LOGIN_SERVER="${{ steps.get-acr.outputs.acr_login_server }}"
          ACR_NAME=$(echo "$ACR_LOGIN_SERVER" | cut -d. -f1)

          az acr login --name "$ACR_NAME"
          docker build -t "$ACR_LOGIN_SERVER/ingestion:latest" ./sourcecode/ingestion
          docker push "$ACR_LOGIN_SERVER/ingestion:latest"

          