name: Terraform Infra + Docker Build + Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-all:
    name: Provision ACR + Build Image + Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply Infra + Apps
        run: |
          set -euxo pipefail
          # Initialize and apply infra (ACR etc)
          terraform -chdir=terraform/infra init
          terraform -chdir=terraform/infra apply -auto-approve

          # Extract ACR login server
          ACR_NAME=$(terraform -chdir=terraform/infra output -raw acr_login_server)
          echo "ACR login server: $ACR_NAME"

          # Build and push Docker image
          az acr login --name $(echo $ACR_NAME | cut -d. -f1)
          docker build -t "$ACR_NAME/ingestion:latest" ./sourcecode/ingestion
          docker push "$ACR_NAME/ingestion:latest"

          # Initialize and deploy app with the pushed image
          terraform -chdir=terraform/apps init
          terraform -chdir=terraform/apps apply -auto-approve -var="acr_login_server=$ACR_NAME"

