name: Terraform Provision & Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  provision-infra:
    name: Provision ACR Infrastructure
    runs-on: ubuntu-latest

    outputs:
      acr_login_server: ${{ steps.acr_output.outputs.acr_login_server }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform/infra init

      - name: Terraform Apply Infra
        run: terraform -chdir=terraform/infra apply -auto-approve

      - name: Get ACR Login Server
        id: acr_output
        run: |
          set -euo pipefail
          # Capture all output (stdout and stderr) from Terraform.
          RAW_ACR_OUTPUT=$(terraform -chdir=terraform/infra output -raw acr_login_server 2>&1)
          
          # Process the raw output to ensure a clean, single line:
          # 1. Remove carriage returns (tr -d '\r').
          # 2. Take only the first line (head -n 1). This is crucial if Terraform or the environment
          #    is unexpectedly printing multiple lines.
          # 3. Use 'cut -d':' -f1' to handle any potential '::debug::' or similar prefixes,
          #    making the extraction robust even if such prefixes reappear.
          ACR_NAME=$(echo "$RAW_ACR_OUTPUT" | tr -d '\r' | head -n 1 | cut -d':' -f1)
          
          # Debug: Print the extracted ACR_NAME before writing to GITHUB_OUTPUT
          echo "::debug::ACR_NAME extracted: '$ACR_NAME'"
          
          # Write the key-value pair to GITHUB_OUTPUT, explicitly quoting the value.
          # This is the most critical change, as it helps GitHub Actions parse the value correctly.
          echo "acr_login_server=\"$ACR_NAME\"" >> "$GITHUB_OUTPUT"
          
          # Debug: Show the content that was written to GITHUB_OUTPUT
          echo "::debug::Content written to GITHUB_OUTPUT:"
          cat "$GITHUB_OUTPUT" || true # '|| true' prevents step failure if file is empty/not found (unlikely here)

      - name: Debug ACR Login Server
        run: echo "::notice::ACR is ${{ steps.acr_output.outputs.acr_login_server }}"

  push-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: provision-infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Build & Push
        run: |
          set -euxo pipefail
          # The ACR variable should now correctly receive the quoted string from the previous job's output.
          ACR="${{ needs.provision-infra.outputs.acr_login_server }}"
          
          # Debug: Print the value of ACR received in this job
          echo "::debug::ACR received in push-image job: '$ACR'"
          
          # Remove quotes from the ACR variable if they were added for output parsing.
          # This ensures 'az acr login' and 'docker build' get a clean registry name.
          CLEAN_ACR=$(echo "$ACR" | sed 's/"//g')
          
          # Extract ACR name for 'az acr login'
          ACR_NAME=$(echo "$CLEAN_ACR" | cut -d. -f1)
          
          az acr login --name "$ACR_NAME"
          docker build -t "$CLEAN_ACR/ingestion:latest" ./sourcecode/ingestion
          docker push "$CLEAN_ACR/ingestion:latest"

  deploy-apps:
    name: Deploy Container App
    runs-on: ubuntu-latest
    needs: push-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          set -euxo pipefail
          terraform -chdir=terraform/apps init
          terraform -chdir=terraform/apps apply -auto-approve -var="acr_login_server=${{ needs.provision-infra.outputs.acr_login_server }}"
