name: Terraform Infra + Docker Build + Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-all:
    name: Provision ACR + Build Image + Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Build and Push Docker Image
        run: |
          set -euxo pipefail

          # Extract the ACR login server from Terraform output
          ACR_LOGIN_SERVER=$(terraform -chdir=terraform/infra output -raw acr_login_server)
          echo "ACR login server: $ACR_LOGIN_SERVER"

          # Extract just the ACR name (e.g., gsacr99ub3e)
          ACR_NAME=$(echo "$ACR_LOGIN_SERVER" | cut -d. -f1)
          echo "ACR name: $ACR_NAME"

          # Login to ACR
          az acr login --name "$ACR_NAME"

          # Build and push the Docker image
          docker build -t "$ACR_LOGIN_SERVER/ingestion:latest" ./sourcecode/ingestion
          docker push "$ACR_LOGIN_SERVER/ingestion:latest"