# .github/workflows/Apply.yml
name: Terraform Provision & Deploy Container Apps

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write # Required for Azure Login with OIDC

jobs:
  provision-infra:
    name: Provision Core Infrastructure
    runs-on: ubuntu-latest

    outputs:
      acr_login_server: ${{ steps.acr_output.outputs.acr_login_server }}
      log_analytics_workspace_id: ${{ steps.logs_output.outputs.log_analytics_workspace_id }}
      resource_group_name: ${{ steps.rg_output.outputs.resource_group_name }}
      location: ${{ steps.location_output.outputs.location }}
      servicebus_namespace_name: ${{ steps.servicebus_output.outputs.servicebus_namespace_name }}
      servicebus_connection_string: ${{ steps.servicebus_output.outputs.servicebus_connection_string }}
      cosmosdb_mongodb_connection_string: ${{ steps.cosmosdb_mongodb_output.outputs.cosmosdb_mongodb_connection_string }}
      cosmosdb_workflow_connection_string: ${{ steps.cosmosdb_workflow_output.outputs.cosmosdb_workflow_connection_string }}
      redis_connection_string: ${{ steps.redis_output.outputs.redis_connection_string }}
      application_insights_connection_string: ${{ steps.appinsights_output.outputs.application_insights_connection_string }}
      key_vault_uri: ${{ steps.keyvault_output.outputs.key_vault_uri }}
      key_vault_id: ${{ steps.keyvault_id_output.outputs.key_vault_id }} # Added Key Vault ID output

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.2 # Pinning Terraform version as suggested by Copilot

      - name: Terraform Init (Infra)
        run: terraform -chdir=terraform/infra init

      - name: Terraform Apply (Infra)
        run: terraform -chdir=terraform/infra apply -auto-approve

      # --- Output Retrieval Steps for Infra ---
      - name: Get ACR Login Server
        id: acr_output
        run: |
          set -euo pipefail
          FULL_COMMAND_OUTPUT=$(terraform -chdir=terraform/infra output -raw acr_login_server 2>&1)
          echo "::debug::FULL_COMMAND_OUTPUT captured: '$FULL_COMMAND_OUTPUT'"
          ACR_NAME=$(echo "$FULL_COMMAND_OUTPUT" | grep -oE '[a-zA-Z0-9.-]+\.azurecr\.io' | head -n 1)
          echo "::debug::ACR_NAME extracted after regex: '$ACR_NAME'"
          printf "acr_login_server=%s\n" "$ACR_NAME" >> "$GITHUB_OUTPUT"
          echo "::debug::Content written to GITHUB_OUTPUT file:"
          cat "$GITHUB_OUTPUT"

      - name: Debug ACR Login Server
        run: echo "::notice::ACR is ${{ steps.acr_output.outputs.acr_login_server }}"

      - name: Get Log Analytics Workspace ID
        id: logs_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Log Analytics Workspace ID
          RAW_LOG_ID_OUTPUT=$(terraform -chdir=terraform/infra output -raw log_analytics_workspace_id 2>&1)
          echo "::debug::Raw Log Analytics Workspace ID Output: '$RAW_LOG_ID_OUTPUT'"
          LOG_ID=$(echo "$RAW_LOG_ID_OUTPUT" | grep -oE '[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}' | head -n 1)
          echo "::debug::Extracted Log Analytics Workspace ID: '$LOG_ID'"
          printf "log_analytics_workspace_id=%s\n" "$LOG_ID" >> "$GITHUB_OUTPUT"

      - name: Get Resource Group Name
        id: rg_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Resource Group Name
          RAW_RG_NAME_OUTPUT=$(terraform -chdir=terraform/infra output -raw resource_group_name 2>&1)
          echo "::debug::Raw Resource Group Name Output: '$RAW_RG_NAME_OUTPUT'"
          RG_NAME=$(echo "$RAW_RG_NAME_OUTPUT" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Resource Group Name: '$RG_NAME'"
          printf "resource_group_name=%s\n" "$RG_NAME" >> "$GITHUB_OUTPUT"

      - name: Get Location
        id: location_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Location
          RAW_LOCATION_OUTPUT=$(terraform -chdir=terraform/infra output -raw location 2>&1)
          echo "::debug::Raw Location Output: '$RAW_LOCATION_OUTPUT'"
          LOCATION=$(echo "$RAW_LOCATION_OUTPUT" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Location: '$LOCATION'"
          printf "location=%s\n" "$LOCATION" >> "$GITHUB_OUTPUT"

      - name: Get Service Bus Namespace Name & Connection String
        id: servicebus_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for namespace name
          RAW_NAMESPACE_OUTPUT=$(terraform -chdir=terraform/infra output -raw servicebus_namespace_name 2>&1)
          echo "::debug::Raw Service Bus Namespace Name Output: '$RAW_NAMESPACE_OUTPUT'"
          NAMESPACE_NAME=$(echo "$RAW_NAMESPACE_OUTPUT" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Service Bus Namespace Name: '$NAMESPACE_NAME'"

          # Debugging: Print the raw output for connection string
          RAW_CONNECTION_STRING_OUTPUT=$(terraform -chdir=terraform/infra output -raw servicebus_connection_string 2>&1)
          echo "::debug::Raw Service Bus Connection String Output: '$RAW_CONNECTION_STRING_OUTPUT'"
          CONNECTION_STRING=$(echo "$RAW_CONNECTION_STRING_OUTPUT" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Service Bus Connection String: '$CONNECTION_STRING'"

          printf "servicebus_namespace_name=%s\n" "$NAMESPACE_NAME" >> "$GITHUB_OUTPUT"
          printf "servicebus_connection_string=%s\n" "$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Get Cosmos DB MongoDB Connection String
        id: cosmosdb_mongodb_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for MongoDB connection string
          RAW_CONNECTION_STRING=$(terraform -chdir=terraform/infra output -raw cosmosdb_mongodb_connection_string 2>&1)
          echo "::debug::Raw Cosmos DB MongoDB Connection String Output: '$RAW_CONNECTION_STRING'"
          CONNECTION_STRING=$(echo "$RAW_CONNECTION_STRING" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Cosmos DB MongoDB Connection String: '$CONNECTION_STRING'"
          printf "cosmosdb_mongodb_connection_string=%s\n" "$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Get Cosmos DB Workflow Connection String
        id: cosmosdb_workflow_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Workflow connection string
          RAW_CONNECTION_STRING=$(terraform -chdir=terraform/infra output -raw cosmosdb_workflow_connection_string 2>&1)
          echo "::debug::Raw Cosmos DB Workflow Connection String Output: '$RAW_CONNECTION_STRING'"
          CONNECTION_STRING=$(echo "$RAW_CONNECTION_STRING" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Cosmos DB Workflow Connection String: '$CONNECTION_STRING'"
          printf "cosmosdb_workflow_connection_string=%s\n" "$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Get Redis Cache Connection String
        id: redis_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Redis connection string
          RAW_CONNECTION_STRING=$(terraform -chdir=terraform/infra output -raw redis_connection_string 2>&1)
          echo "::debug::Raw Redis Connection String Output: '$RAW_CONNECTION_STRING'"
          CONNECTION_STRING=$(echo "$RAW_CONNECTION_STRING" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Redis Connection String: '$CONNECTION_STRING'"
          printf "redis_connection_string=%s\n" "$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Get Application Insights Connection String
        id: appinsights_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Application Insights connection string
          RAW_CONNECTION_STRING=$(terraform -chdir=terraform/infra output -raw application_insights_connection_string 2>&1)
          echo "::debug::Raw Application Insights Connection String Output: '$RAW_CONNECTION_STRING'"
          CONNECTION_STRING=$(echo "$RAW_CONNECTION_STRING" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Application Insights Connection String: '$CONNECTION_STRING'"
          printf "application_insights_connection_string=%s\n" "$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Get Key Vault URI
        id: keyvault_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Key Vault URI
          RAW_KEY_VAULT_URI=$(terraform -chdir=terraform/infra output -raw key_vault_uri 2>&1)
          echo "::debug::Raw Key Vault URI Output: '$RAW_KEY_VAULT_URI'"
          KEY_VAULT_URI=$(echo "$RAW_KEY_VAULT_URI" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Key Vault URI: '$KEY_VAULT_URI'"
          printf "key_vault_uri=%s\n" "$KEY_VAULT_URI" >> "$GITHUB_OUTPUT"

      - name: Get Key Vault ID
        id: keyvault_id_output
        run: |
          set -euo pipefail
          # Debugging: Print the raw output for Key Vault ID
          RAW_KEY_VAULT_ID=$(terraform -chdir=terraform/infra output -raw key_vault_id 2>&1)
          echo "::debug::Raw Key Vault ID Output: '$RAW_KEY_VAULT_ID'"
          KEY_VAULT_ID=$(echo "$RAW_KEY_VAULT_ID" | head -n 1 | tr -d '\r')
          echo "::debug::Extracted Key Vault ID: '$KEY_VAULT_ID'"
          printf "key_vault_id=%s\n" "$KEY_VAULT_ID" >> "$GITHUB_OUTPUT"

  build-and-push-images:
    name: Build and Push Container Images
    runs-on: ubuntu-latest
    needs: provision-infra
    outputs:
      ingestion_image: ${{ steps.set_ingestion_image.outputs.image_name }}
      workflow_image: ${{ steps.set_workflow_image.outputs.image_name }}
      package_image: ${{ steps.set_package_image.outputs.image_name }}
      drone_scheduler_image: ${{ steps.set_drone_scheduler_image.outputs.image_name }}
      delivery_image: ${{ steps.set_delivery_image.outputs.image_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ needs.provision-infra.outputs.acr_login_server }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Ingestion Image
        run: |
          docker build -t ${{ needs.provision-infra.outputs.acr_login_server }}/ingestion-service:${{ github.sha }} ./src/Ingestion
          docker push ${{ needs.provision-infra.outputs.acr_login_server }}/ingestion-service:${{ github.sha }}
      - name: Set Ingestion Image Output
        id: set_ingestion_image
        run: echo "image_name=${{ needs.provision-infra.outputs.acr_login_server }}/ingestion-service:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Workflow Image
        run: |
          docker build -t ${{ needs.provision-infra.outputs.acr_login_server }}/workflow-service:${{ github.sha }} ./src/Workflow
          docker push ${{ needs.provision-infra.outputs.acr_login_server }}/workflow-service:${{ github.sha }}
      - name: Set Workflow Image Output
        id: set_workflow_image
        run: echo "image_name=${{ needs.provision-infra.outputs.acr_login_server }}/workflow-service:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Package Image
        run: |
          docker build -t ${{ needs.provision-infra.outputs.acr_login_server }}/package-service:${{ github.sha }} ./src/Package
          docker push ${{ needs.provision-infra.outputs.acr_login_server }}/package-service:${{ github.sha }}
      - name: Set Package Image Output
        id: set_package_image
        run: echo "image_name=${{ needs.provision-infra.outputs.acr_login_server }}/package-service:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Drone Scheduler Image
        run: |
          docker build -t ${{ needs.provision-infra.outputs.acr_login_server }}/drone-scheduler-service:${{ github.sha }} ./src/DroneScheduler
          docker push ${{ needs.provision-infra.outputs.acr_login_server }}/drone-scheduler-service:${{ github.sha }}
      - name: Set Drone Scheduler Image Output
        id: set_drone_scheduler_image
        run: echo "image_name=${{ needs.provision-infra.outputs.acr_login_server }}/drone-scheduler-service:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Delivery Image
        run: |
          docker build -t ${{ needs.provision-infra.outputs.acr_login_server }}/delivery-service:${{ github.sha }} ./src/Delivery
          docker push ${{ needs.provision-infra.outputs.acr_login_server }}/delivery-service:${{ github.sha }}
      - name: Set Delivery Image Output
        id: set_delivery_image
        run: echo "image_name=${{ needs.provision-infra.outputs.acr_login_server }}/delivery-service:${{ github.sha }}" >> "$GITHUB_OUTPUT"

  deploy-apps:
    name: Deploy Container Apps
    runs-on: ubuntu-latest
    needs: [provision-infra, build-and-push-images]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.2 # Pinning Terraform version

      - name: Terraform Init (Apps)
        run: terraform -chdir=terraform/apps init

      - name: Set Resource Group Prefix for Apps
        id: set_rg_prefix
        run: |
          set -euo pipefail
          # Derive the resource_group_name_prefix from the provisioned resource_group_name
          RG_NAME="${{ needs.provision-infra.outputs.resource_group_name }}"
          RG_NAME_PREFIX=$(echo "$RG_NAME" | sed -E 's/^aca-rg-//')
          printf "resource_group_name_prefix=%s\n" "$RG_NAME_PREFIX" >> "$GITHUB_OUTPUT"

      - name: Terraform Apply (Apps)
        run: |
          set -euo pipefail # Kept for robustness
          terraform -chdir=terraform/apps apply -auto-approve \
            -var="location=${{ needs.provision-infra.outputs.location }}" \
            -var="resource_group_name=${{ needs.provision-infra.outputs.resource_group_name }}" \
            -var="resource_group_name_prefix=${{ steps.set_rg_prefix.outputs.resource_group_name_prefix }}" \
            -var="log_analytics_workspace_id=${{ needs.provision-infra.outputs.log_analytics_workspace_id }}" \
            -var="acr_login_server=${{ needs.provision-infra.outputs.acr_login_server }}" \
            -var="servicebus_namespace_name=${{ needs.provision-infra.outputs.servicebus_namespace_name }}" \
            -var="servicebus_connection_string=${{ needs.provision-infra.outputs.servicebus_connection_string }}" \
            -var="cosmosdb_mongodb_connection_string=${{ needs.provision-infra.outputs.cosmosdb_mongodb_connection_string }}" \
            -var="cosmosdb_workflow_connection_string=${{ needs.provision-infra.outputs.cosmosdb_workflow_connection_string }}" \
            -var="redis_connection_string=${{ needs.provision-infra.outputs.redis_connection_string }}" \
            -var="application_insights_connection_string=${{ needs.provision-infra.outputs.application_insights_connection_string }}" \
            -var="key_vault_uri=${{ needs.provision-infra.outputs.key_vault_uri }}" \
            -var="key_vault_id=${{ needs.provision-infra.outputs.key_vault_id }}" \
            -var="ingestion_image=${{ needs.build-and-push-images.outputs.ingestion_image }}" \
            -var="workflow_image=${{ needs.build-and-push-images.outputs.workflow_image }}" \
            -var="package_image=${{ needs.build-and-push-images.outputs.package_image }}" \
            -var="drone_scheduler_image=${{ needs.build-and-push-images.outputs.drone_scheduler_image }}" \
            -var="delivery_image=${{ needs.build-and-push-images.outputs.delivery_image }}"

      - name: Get Ingestion App FQDN
        run: |
          set -euo pipefail # Kept for robustness
          INGESTION_FQDN=$(terraform -chdir=terraform/apps output -raw ingestion_fqdn)
          echo "Ingestion App FQDN: $INGESTION_FQDN"